# Generated by Django 3.0.2 on 2020-03-02 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Mood Disorder', 'Mood Disorder'), ('Behavior Disorder', 'Behavior Disorder'), ('Autism Spectrum Disorder', 'Autism Spectrum Disorder'), ('Eating Disorder', 'Eating Disorder'), ('Parenting', 'Parenting'), ('Other Children Behavior', 'Other Children Behavior')], max_length=100)),
                ('descn', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('num_posts', models.IntegerField(default=0)),
                ('num_replies', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Category')),
            ],
            options={
                'ordering': ('-created_on', 'updated_on'),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_ip', models.GenericIPAddressField()),
                ('subject', models.CharField(max_length=999)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('context', models.TextField(default='')),
                ('num_views', models.IntegerField(default=0)),
                ('num_replies', models.PositiveSmallIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('last_reply_on', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='forum.Category')),
                ('forum', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='forum.Forum')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'ordering': ('-last_reply_on',),
                'get_latest_by': 'created_on',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_ip', models.GenericIPAddressField()),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Post')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
