# Generated by Django 3.0.2 on 2020-03-03 23:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, default=uuid.uuid4, max_length=10, unique=True)),
                ('service', models.IntegerField(blank=True, choices=[('Depression', 'Depression'), ('ADHD', 'ADHD'), ('Autism', 'Autism'), ('Anxiety', 'Anxiety'), ('Bipolar', 'Bipolar'), ('Behavior', 'Behavior'), ('Eating Disorder', 'Eating Disorder'), ('Others', 'Others')])),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(choices=[('09:00:00', '09 AM'), ('10:00:00', '10 AM'), ('11:00:00', '11 AM'), ('13:00:00', '01 PM'), ('14:00:00', '02 PM'), ('15:00:00', '03 PM'), ('16:00:00', '04 PM')])),
                ('note', models.TextField(blank=True, max_length=5000)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('has_perscription', models.BooleanField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Perscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, unique=True)),
                ('dose', models.CharField(blank=True, max_length=100)),
                ('instruction', models.TextField(blank=True, max_length=5000)),
                ('sideaffect', models.TextField(blank=True, max_length=5000)),
                ('link', models.URLField(max_length=2000)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Appointment')),
            ],
        ),
    ]
