# Generated by Django 3.0.2 on 2020-03-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20200305_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Depression', 'Depression'), ('ADHD', 'ADHD'), ('Autism', 'Autism'), ('Anxiety', 'Anxiety'), ('Bipolar', 'Bipolar'), ('Behavior', 'Behavior'), ('Eating Disorder', 'Eating Disorder'), ('Others', 'Others')], max_length=250),
        ),
    ]
