# Generated by Django 3.0.2 on 2020-03-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20200305_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='has_perscription',
            field=models.BooleanField(default=False),
        ),
    ]
