# Generated by Django 3.0.2 on 2020-03-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='body_store',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='posted_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
