# Generated by Django 3.0.2 on 2020-03-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200303_0014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
